### ISSUE TITLE
通过多张图片逐压缩级别对比后发现2.1.3版本不如1.2.3版本压缩清晰

### ISSUE THREAD

**Issue by ArtliveBear** [richhost/pixzip-lite#18]
您好，通过多张图片逐压缩级别对比后发现2.1.3版本不如1.2.3版本压缩清晰，虽然2.1.3版本大大加大了压缩的尺寸占用空间，但是发现2.1.3版本压缩等级1时，不如1.2.3版本的压缩等级4的清晰，而且此时2.1.3版本压缩出来的图片尺寸要比后者大一些，更大登基的压缩出来的清晰度就更不如1.2.3版本的了。希望开发者能够进一步多多对比压缩度和清晰度对比。

**Comment by richhost** [comment]
The new version adjusts the compression quality.
